FROM amazonlinux:2017.03

RUN yum install -y gcc gcc-c++ make openssl-devel zip
RUN curl https://nodejs.org/download/release/v6.10.3/node-v6.10.3-linux-x64.tar.gz | tar xz -C /usr --strip-components=1

WORKDIR /builder

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN zip -9qyr /output.zip .
CMD cat /output.zip | base64
